behaviors:
  short_poca:
    trainer_type: poca
    hyperparameters:
      batch_size: 64
      buffer_size: 640
      learning_rate: 0.0003
      beta: 0.05
      epsilon: 0.2
      lambd: 0.5
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
    keep_checkpoints: 40
    checkpoint_interval: 2000000
    max_steps: 500000000
    time_horizon: 1000
    summary_freq: 50000
    threaded: false
    self_play:
      save_steps: 500000
      team_change: 1000000
      swap_steps: 200000
      window: 100
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

  long_poca:
    trainer_type: poca
    hyperparameters:
      batch_size: 64
      buffer_size: 640
      learning_rate: 0.0003
      beta: 0.05
      epsilon: 0.2
      lambd: 0.5
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
    keep_checkpoints: 40
    checkpoint_interval: 2000000
    max_steps: 500000000
    time_horizon: 1000
    summary_freq: 50000
    threaded: false
    self_play:
      save_steps: 500000
      team_change: 1000000
      swap_steps: 200000
      window: 100
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

  short_ppo:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 640
      learning_rate: 0.0003
      beta: 0.05
      epsilon: 0.2
      lambd: 0.5
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
      curiosity:
        strength: 0.2
        gamma: 0.99
        encoding_size: 39
    keep_checkpoints: 50
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 20000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

  long_ppo:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 640
      learning_rate: 0.0003
      beta: 0.05
      epsilon: 0.2
      lambd: 0.5
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
      goal_conditioning_type: none
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
      curiosity:
        strength: 0.2
        gamma: 0.99
        encoding_size: 39
    keep_checkpoints: 50
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 20000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

env_settings:
  num_envs: 1